baseurl: "/"
languageCode: "zh-CN"
title: "找不着北"
# subtitle: "engineer"
theme: "hello-friend"
paginate: 5
copyright: "找不着北 © 2020"
metaDataFormat: "yaml"
disqusShortname: "greyby"
googleAnalytics: UA-177281432-1

params:  
  contentTypeName: "post"
  defaultTheme: "dark"
  showMenuItems: 2
  showReadingTime: false
  rssFullText: true

menu:
  main:
    - identifier: "home"
      name: "Home"
      url: "/"
    - identifier: "about"
      name: "About"
      url: "/about"

permalinks:
  post: /:year/:month/:day/:slug/

languages:
  en:
    menuMore: ""
    readMore: "Read More"
    readOtherPosts: "Read other posts"
    newerPosts: "Newer Posts"
    olderPosts: "Older Posts"
    dateFormatSingle: "2006-01-02"
    dateFormatList: "2006-01-02"
    params:
      logo:
        logoText: "找不着北"
        logoHomeLink: "/"